keywords:
  - "夢ノ結唱"
  - "梦的结唱"
  - "Syntheiszer ROSE"
  - "Synthesizer POPY"
  - "Synthesizer PASTEL"
  - "Synthesizer HALO"
  - "Synthesizer AVER"
  - "ksm"
  - "ykn"
  - "kkr"
  - "香澄"
  - "友希那"
  - "丸山彩"
  - "弦卷心"
  - "三角初华"
name: 梦的结唱9
time_start: "2025-11-27"
time_end: "2026-02-28"
video_zone_type: 0
